blank_issues_enabled: false
contact_links:
  - name: Private, urgent or personal matters
    url: https://github.com/hareshsuppiah/handbook-for-the-recently-enrolled/blob/main/SUPPORT.md
    about: Do not post these publicly. Find the appropriate local support or reporting route.
