#!/usr/bin/env python3
"""Build the page-by-page xkcd visual system from an editorial mapping."""

from __future__ import annotations

import argparse
import csv
import json
import re
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "assets/xkcd"
META_DIR = ROOT / "research/xkcd-source-metadata"

# Pages listed here receive an editorially selected xkcd comic. A page may be
# deliberately absent when another cleared visual is planned or no visual adds
# enough teaching value. Selection notes stay outside the public repository.
ASSIGNMENTS: dict[str, int] = {'chapters/part-01/02-first-90-days.qmd': 1425, 'chapters/part-05/13-design-alignment.qmd': 552, 'chapters/part-07/20-data-states-provenance.qmd': 2582, 'chapters/part-08/24-git-github-ai.qmd': 1597, 'chapters/part-09/25-milestones-weekly-work.qmd': 1205, 'chapters/part-09/27-collaboration-handoffs-scope.qmd': 1782, 'chapters/part-10/30-publishing-review-communication.qmd': 2304}

ALT_TEXT: dict[int, str] = {1425: 'A programmer explains that locating a photo in a national park is straightforward, while recognising a bird in it may need years of research. Apparently similar tasks can need very different amounts of work.', 552: 'One person stopped believing correlation proves causation after a statistics class. When a friend credits the class, the person hesitates: the same causal caution applies to that explanation.', 2582: 'A person proposes analysing a pile of data; another points out that analysis produces more data. Derived files need names and records too.', 1597: 'A Git user can repeat commands but cannot explain them, and responds to errors by downloading a fresh copy. The joke recognises why practising a small recovery is more useful than memorising commands.', 1205: 'A table compares how often a task occurs with time saved per run to estimate how much time can be spent improving it. For example, saving one minute each day gives about one day over five years in this illustrative calculation.', 1782: 'A team repeatedly changes chat platforms while one member stays with an older system. More channels do not guarantee a shared record.', 2304: 'A news presenter repeatedly rephrases the status of an unreviewed paper before calling it a PDF. Publication format alone does not establish peer review.'}


def book_pages() -> list[str]:
    config = yaml.safe_load((ROOT / "_quarto.yml").read_text())
    pages: list[str] = []

    def walk(items: list[object]) -> None:
        for item in items:
            if isinstance(item, str):
                pages.append(item)
            elif isinstance(item, dict):
                walk(item.get("chapters", []))

    walk(config["book"]["chapters"])
    return pages


def fetch_metadata(comic_id: int) -> dict[str, object]:
    META_DIR.mkdir(parents=True, exist_ok=True)
    path = META_DIR / f"{comic_id}.json"
    if not path.exists():
        url = f"https://xkcd.com/{comic_id}/info.0.json"
        with urllib.request.urlopen(url) as response:
            path.write_bytes(response.read())
    return json.loads(path.read_text())


def download_image(meta: dict[str, object]) -> str:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    comic_id = int(meta["num"])
    source = str(meta["img"])
    suffix = Path(source).suffix or ".png"
    safe = re.sub(r"[^a-z0-9]+", "-", str(meta["safe_title"]).lower()).strip("-")
    filename = f"{comic_id}-{safe}{suffix}"
    path = ASSET_DIR / filename
    if not path.exists():
        with urllib.request.urlopen(source) as response:
            path.write_bytes(response.read())
    return f"assets/xkcd/{filename}"


def lua_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_lua_data(rows: list[dict[str, str]]) -> None:
    out = ["-- Generated by scripts/build_page_comics.py; do not edit by hand.", "return {"]
    for row in rows:
        out.append(f"  [{lua_string(row['page_path'])}] = {{")
        out.append(f"    page_path = {lua_string(row['page_path'])},")
        for key in ("comic_id", "title", "asset_path", "alt_text"):
            out.append(f"    {key} = {lua_string(row[key])},")
        out.append("  },")
        out.append(f"  [{lua_string('title:' + row['page_title'])}] = {{")
        out.append(f"    page_path = {lua_string(row['page_path'])},")
        for key in ("comic_id", "title", "asset_path", "alt_text"):
            out.append(f"    {key} = {lua_string(row[key])},")
        out.append("  },")
    out.append("}")
    (ROOT / "filters/page-comics-data.lua").write_text("\n".join(out) + "\n")


def write_register_include(rows: list[dict[str, str]]) -> None:
    placements: dict[str, list[str]] = defaultdict(list)
    titles: dict[str, str] = {}
    for row in rows:
        placements[row["comic_id"]].append(row["page_title"])
        titles[row["comic_id"]] = row["title"]
    lines = [
        "## The xkcd comics used in this handbook",
        "",
        "Every embedded xkcd comic is by Randall Munroe and is reused from "
        "[xkcd](https://xkcd.com/) under the "
        "[Creative Commons Attribution–NonCommercial 2.5 licence](https://creativecommons.org/licenses/by-nc/2.5/). "
        "The comics are excluded from the handbook's CC BY 4.0 content licence. "
        "Each appearance links to the original comic and transcript.",
        "",
        "| Comic | Used on |",
        "|---|---|",
    ]
    for comic_id in sorted(placements, key=int):
        pages = placements[comic_id]
        page_text = "; ".join(pages)
        lines.append(f"| [xkcd #{comic_id}: {titles[comic_id]}](https://xkcd.com/{comic_id}/) | {page_text} |")
    lines.extend([
        "",
        "The machine-readable page-by-page placement and asset path are recorded in the "
        "[`page-visuals register`](https://github.com/hareshsuppiah/handbook-for-the-recently-enrolled/blob/main/research/page-visuals.csv).",
        "",
    ])
    (ROOT / "includes/xkcd-register.qmd").write_text("\n".join(lines))


def update_visual_register(unique: dict[int, tuple[dict[str, object], str]]) -> None:
    path = ROOT / "research/visual-assets-register.csv"
    with path.open(newline="", encoding="utf-8") as handle:
        existing = [row for row in csv.DictReader(handle) if not row["asset_id"].startswith("VIS-XKCD-")]
        fieldnames = list(existing[0].keys())
    for comic_id in sorted(unique):
        meta, asset_path = unique[comic_id]
        existing.append({
            "asset_id": f"VIS-XKCD-{comic_id}",
            "path": asset_path,
            "title": f"xkcd #{comic_id}: {meta['safe_title']}",
            "creator_or_rightsholder": "Randall Munroe / xkcd",
            "source_url": f"https://xkcd.com/{comic_id}/",
            "license_or_reuse_basis": "Creative Commons Attribution-NonCommercial 2.5; excluded from the handbook CC BY 4.0 licence",
            "license_url": "https://creativecommons.org/licenses/by-nc/2.5/",
            "changes": "Resized responsively by the website; otherwise unmodified",
            "alt_text": ALT_TEXT[comic_id],
            "caption": f"xkcd #{comic_id}, {meta['safe_title']}, by Randall Munroe",
            "placement": "See research/page-visuals.csv",
            "date_checked": "2026-08-30",
            "review_status": "approved for non-commercial attributed use",
        })
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(existing)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fetch", action="store_true", help="Fetch missing official metadata and images")
    args = parser.parse_args()

    pages = book_pages()
    extra = sorted(set(ASSIGNMENTS) - set(pages))
    if extra:
        raise SystemExit(f"Mapping contains pages outside the Quarto book: {extra}")

    metadata: dict[int, dict[str, object]] = {}
    assets: dict[int, str] = {}
    for comic_id in sorted(set(ASSIGNMENTS.values())):
        meta_path = META_DIR / f"{comic_id}.json"
        if not meta_path.exists() and not args.fetch:
            raise SystemExit(f"Missing {meta_path}; rerun with --fetch")
        meta = fetch_metadata(comic_id)
        asset = download_image(meta) if args.fetch else next(ASSET_DIR.glob(f"{comic_id}-*"), None)
        if asset is None:
            raise SystemExit(f"Missing local image for xkcd #{comic_id}; rerun with --fetch")
        metadata[comic_id] = meta
        assets[comic_id] = asset if isinstance(asset, str) else str(asset.relative_to(ROOT))

    rows: list[dict[str, str]] = []
    for page in pages:
        if page not in ASSIGNMENTS:
            continue
        comic_id = ASSIGNMENTS[page]
        source = (ROOT / page).read_text()
        title_match = re.search(r'^title:\s*["\']?(.*?)["\']?\s*$', source, re.M)
        if not title_match:
            raise SystemExit(f"No title in {page}")
        rows.append({
            "page_path": page,
            "page_title": title_match.group(1),
            "comic_id": str(comic_id),
            "alt_text": ALT_TEXT[comic_id],
            "title": str(metadata[comic_id]["safe_title"]),
            "asset_path": assets[comic_id],
            "source_url": f"https://xkcd.com/{comic_id}/",
            "creator": "Randall Munroe / xkcd",
            "license": "CC BY-NC 2.5",
            "license_url": "https://creativecommons.org/licenses/by-nc/2.5/",
        })

    with (ROOT / "research/page-visuals.csv").open("w", newline="", encoding="utf-8") as handle:
        fields = ["page_path", "page_title", "comic_id", "title", "asset_path", "source_url", "creator", "license", "license_url"]
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)

    write_lua_data(rows)
    write_register_include(rows)
    update_visual_register({comic_id: (metadata[comic_id], assets[comic_id]) for comic_id in metadata})

    counts = Counter(row["comic_id"] for row in rows)
    print(f"pages={len(rows)} unique_comics={len(counts)}")
    print("most_reused=" + ",".join(f"{comic}:{count}" for comic, count in counts.most_common(8)))


if __name__ == "__main__":
    main()
